name: Check code
on:
  pull_request:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust nightly
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2023-12-21
          components: rustfmt,clippy
          targets: wasm32-unknown-unknown

      - name: Add rust-src
        run: rustup component add rust-src --toolchain nightly-2023-12-21-x86_64-unknown-linux-gnu

      - name: Rust Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-rust-release-v6-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-rust-release-v6
            ${{ runner.os }}-rust-release

      - name: Run checks
        run: .github/workflows/check.sh

      - uses: dprint/check@v2.2
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust nightly
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2023-12-21
          components: rustfmt,clippy
          targets: wasm32-unknown-unknown
        
      - name: Add rust-src
        run: rustup component add rust-src --toolchain nightly-2023-12-21-x86_64-apple-darwin

      - name: Rust Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-rust-release-v5-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-rust-release-v5
            ${{ runner.os }}-rust-release

      - name: Run checks
        run: .github/workflows/check.sh

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust nightly
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2023-12-21
          components: rustfmt,clippy
          targets: wasm32-unknown-unknown
        
      - name: Add rust-src
        run: rustup component add rust-src --toolchain nightly-2023-12-21-x86_64-pc-windows-msvc

      - name: Rust Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-rust-release-v5-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-rust-release-v5
            ${{ runner.os }}-rust-release
      - name: install wget
        shell: bash
        run: choco install wget
        
      - name: Run checks
        shell: bash
        run: .github/workflows/check.sh
